name: Build and publish Wakatee Web App

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Build image
        run: docker build -t cashtoken/cicdtest .
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600
      - name: Tag image
        run:
          docker tag cashtoken/cicdtest registry.digitalocean.com/cicdtest/cicdtest-web-app
      - name: Push image to DO Container Registry
        run: docker push registry.digitalocean.com/cicdtest/cicdtest-web-app
