name: CI/CD Learning Staging

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH and deploy node app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_STAGING_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY}}
        port: ${{ secrets.DEPLOY_PORT }}
        passphrase: ${{ secrets.DEPLOY_PASSPHRASE }}
        script: |
          cd node-proxy
          git stash
          git checkout staging
          git pull origin staging
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          nvm use 18
          npm i
          pm2 restart app-staging-start.json --time --watch false
