name: CI/CD Learning Prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH and deploy node app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_PROD_USER }}
        password: ${{ secrets.DEPLOY_PASSWORD}}
        port: ${{ secrets.DEPLOY_PORT }}
        script: |
          cd cicd-intro
          git stash
          git checkout main
          git pull origin main
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          nvm use 18
          npm i
          pm2 restart app-prod-start.json --time --watch false
